[Eth]
    NetworkAddress    = "http://127.0.0.1:8545"
    BridgeAddress     = "0x48Fd3D532254255c921b69286daA5e1938645baA"
    PrivateKey        = "60f3849d7c8d93dfce1947d17c34be3e4ea974e74e15ce877f0df34d7192efab"

[Elrond]
    NetworkAddress    = "http://localhost:7950"
    BridgeAddress     = "erd1qqqqqqqqqqqqqpgqfzydqmdw7m2vazsp6u5p95yxz76t2p9rd8ss0zp9ts"
    PrivateKeyPath    = "../mytestnet/testnet/wallets/users/bob.pem"

[P2P]
    Port              = "10000"
    Seed              = "seed"
    InitialPeerList   = []