[Eth]
    NetworkAddress    = "http://127.0.0.1:8545"
    BridgeAddress     = "0x9ec0A85A0905020229338FA33D86593B8C724faB"

[Elrond]
    NetworkAddress    = "http://localhost:7950"
    BridgeAddress     = "erd1qqqqqqqqqqqqqpgqfzydqmdw7m2vazsp6u5p95yxz76t2p9rd8ss0zp9ts"
    PrivateKeyPath    = "../mytestnet/testnet/wallets/users/bob.pem"

[P2P]
    Port              = "10000"
    Seed              = "seed"
    InitialPeerList   = []