[Eth]
NetworkAddress = "http://127.0.0.1:8545"
BridgeAddress = "0xAe8e11E48b04E13B5211ADf94FB856254A9C9CC8"
PrivateKey = "25b96cce574b43c1bb62b461826ed6bf60d16c3951c88b7b83947ea3ec03d82f"

[Elrond]
NetworkAddress = "https://testnet-gateway.elrond.com"
BridgeAddress = "erd1qqqqqqqqqqqqqpgqg5xncpm6kp46zs3kuu6h7xr858cntxh8yu0sc5556f"
PrivateKey = "/home/calin/Projects/elrond/testnet-wallets/ion.pem"

[P2P]
Port = "10000"
Seed = "seed"
InitialPeerList = []
