[Eth]
NetworkAddress = "http://127.0.0.1:8545"
BridgeAddress = "0x721a1cf6560B80058EB47f94E477e998A5CB1216"
PrivateKey = "25b96cce574b43c1bb62b461826ed6bf60d16c3951c88b7b83947ea3ec03d82f"

[Elrond]
NetworkAddress = "https://testnet-gateway.elrond.com"
BridgeAddress = "erd1qqqqqqqqqqqqqpgq9m7lw2wv2sjqau3dg3vv4vtpx7gssjfnyu0s8qmjwf"
PrivateKey = "/home/calin/Projects/elrond/testnet-wallets/ion.pem"

[P2P]
Port = "10000"
Seed = "seed"
InitialPeerList = []
