[Eth]
NetworkAddress = "http://127.0.0.1:8545"
BridgeAddress = "0xc6BDb1E9606887da404a722487a47A7D15D238f0"
PrivateKey = "25b96cce574b43c1bb62b461826ed6bf60d16c3951c88b7b83947ea3ec03d82f"

[Elrond]
NetworkAddress = "https://testnet-gateway.elrond.com"
BridgeAddress = "erd1qqqqqqqqqqqqqpgquxv6eew4nzmcy0sr4r939p6wzcm0zkc8d8ssjspkj7"
PrivateKey = "/home/calin/Projects/elrond/elrond-eth-bridge/mytestnet/mycounter/wallets/users/bob.pem"

[P2P]
Port = "10000"
Seed = "seed"
InitialPeerList = []
